// Copyright 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//
// gRPC service definition for the Attestation Service (Verifier).
// This is the external Verifier in the IETF RATS architecture (RFC 9334).
// It receives evidence from the CVM Agent (via virt-handler), verifies it
// against reference values, and issues attestation result tokens.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: attestationproto/v1/attestation.proto

package attestationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verdict is the trust verdict for a container.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_TRUSTED     Verdict = 1
	Verdict_VERDICT_UNTRUSTED   Verdict = 2
	Verdict_VERDICT_STALE       Verdict = 3
	Verdict_VERDICT_UNKNOWN     Verdict = 4
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_TRUSTED",
		2: "VERDICT_UNTRUSTED",
		3: "VERDICT_STALE",
		4: "VERDICT_UNKNOWN",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_TRUSTED":     1,
		"VERDICT_UNTRUSTED":   2,
		"VERDICT_STALE":       3,
		"VERDICT_UNKNOWN":     4,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_attestationproto_v1_attestation_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_attestationproto_v1_attestation_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{0}
}

// VerifyWorkloadRequest carries per-workload evidence produced by trustd.
type VerifyWorkloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable workload identity — the refstore lookup key. Must match the
	// `workload_id` used by trustd.AttestWorkload.
	WorkloadId string `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// Raw TDX quote bytes (signed by Intel DCAP; contains RTMR[0..3] + report_data).
	TdQuote []byte `protobuf:"bytes,2,opt,name=td_quote,json=tdQuote,proto3" json:"td_quote,omitempty"`
	// Bytes of the kernel's per-container event log at
	// /sys/kernel/security/ima/container_rtmr/<mangled-cgroup>. Single
	// JSON object per file.
	EventLog []byte `protobuf:"bytes,3,opt,name=event_log,json=eventLog,proto3" json:"event_log,omitempty"`
	// Verifier-chosen nonce (hex-encoded). Must match what trustd used for
	// report_data construction.
	NonceHex string `protobuf:"bytes,4,opt,name=nonce_hex,json=nonceHex,proto3" json:"nonce_hex,omitempty"`
	// Peer public key bytes (empty = no channel binding).
	PeerPk        []byte `protobuf:"bytes,5,opt,name=peer_pk,json=peerPk,proto3" json:"peer_pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWorkloadRequest) Reset() {
	*x = VerifyWorkloadRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWorkloadRequest) ProtoMessage() {}

func (x *VerifyWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWorkloadRequest.ProtoReflect.Descriptor instead.
func (*VerifyWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyWorkloadRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *VerifyWorkloadRequest) GetTdQuote() []byte {
	if x != nil {
		return x.TdQuote
	}
	return nil
}

func (x *VerifyWorkloadRequest) GetEventLog() []byte {
	if x != nil {
		return x.EventLog
	}
	return nil
}

func (x *VerifyWorkloadRequest) GetNonceHex() string {
	if x != nil {
		return x.NonceHex
	}
	return ""
}

func (x *VerifyWorkloadRequest) GetPeerPk() []byte {
	if x != nil {
		return x.PeerPk
	}
	return nil
}

// VerifyWorkloadResponse carries the verdict plus structured per-check breakdown.
type VerifyWorkloadResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Verdict Verdict                `protobuf:"varint,1,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// JWT attestation result token (signed by this service) — empty if
	// the verdict is not TRUSTED.
	AttestationToken string                       `protobuf:"bytes,3,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	Details          *WorkloadVerificationDetails `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	// Policy-selected remediation action (`none|alert|restart|kill`).
	PolicyAction  string `protobuf:"bytes,5,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWorkloadResponse) Reset() {
	*x = VerifyWorkloadResponse{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWorkloadResponse) ProtoMessage() {}

func (x *VerifyWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWorkloadResponse.ProtoReflect.Descriptor instead.
func (*VerifyWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyWorkloadResponse) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *VerifyWorkloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyWorkloadResponse) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

func (x *VerifyWorkloadResponse) GetDetails() *WorkloadVerificationDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *VerifyWorkloadResponse) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

// WorkloadVerificationDetails provides insight into which subcheck failed.
type WorkloadVerificationDetails struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	QuoteSignatureValid      bool                   `protobuf:"varint,1,opt,name=quote_signature_valid,json=quoteSignatureValid,proto3" json:"quote_signature_valid,omitempty"`
	QuoteVerificationSkipped bool                   `protobuf:"varint,2,opt,name=quote_verification_skipped,json=quoteVerificationSkipped,proto3" json:"quote_verification_skipped,omitempty"`
	// RTMR[2] in the quote is an enrolled TCB reference (the kernel is genuine).
	TcbMatches bool `protobuf:"varint,3,opt,name=tcb_matches,json=tcbMatches,proto3" json:"tcb_matches,omitempty"`
	// report_data = SHA384(nonce) || SHA384(peer_pk or 0s).
	ReportDataValid    bool     `protobuf:"varint,4,opt,name=report_data_valid,json=reportDataValid,proto3" json:"report_data_valid,omitempty"`
	MatchedCount       int32    `protobuf:"varint,5,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	UnknownCount       int32    `protobuf:"varint,6,opt,name=unknown_count,json=unknownCount,proto3" json:"unknown_count,omitempty"`
	MissingCount       int32    `protobuf:"varint,7,opt,name=missing_count,json=missingCount,proto3" json:"missing_count,omitempty"`
	AllRequiredPresent bool     `protobuf:"varint,8,opt,name=all_required_present,json=allRequiredPresent,proto3" json:"all_required_present,omitempty"`
	UnknownFiles       []string `protobuf:"bytes,9,rep,name=unknown_files,json=unknownFiles,proto3" json:"unknown_files,omitempty"`
	MissingFiles       []string `protobuf:"bytes,10,rep,name=missing_files,json=missingFiles,proto3" json:"missing_files,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkloadVerificationDetails) Reset() {
	*x = WorkloadVerificationDetails{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadVerificationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadVerificationDetails) ProtoMessage() {}

func (x *WorkloadVerificationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadVerificationDetails.ProtoReflect.Descriptor instead.
func (*WorkloadVerificationDetails) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadVerificationDetails) GetQuoteSignatureValid() bool {
	if x != nil {
		return x.QuoteSignatureValid
	}
	return false
}

func (x *WorkloadVerificationDetails) GetQuoteVerificationSkipped() bool {
	if x != nil {
		return x.QuoteVerificationSkipped
	}
	return false
}

func (x *WorkloadVerificationDetails) GetTcbMatches() bool {
	if x != nil {
		return x.TcbMatches
	}
	return false
}

func (x *WorkloadVerificationDetails) GetReportDataValid() bool {
	if x != nil {
		return x.ReportDataValid
	}
	return false
}

func (x *WorkloadVerificationDetails) GetMatchedCount() int32 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *WorkloadVerificationDetails) GetUnknownCount() int32 {
	if x != nil {
		return x.UnknownCount
	}
	return 0
}

func (x *WorkloadVerificationDetails) GetMissingCount() int32 {
	if x != nil {
		return x.MissingCount
	}
	return 0
}

func (x *WorkloadVerificationDetails) GetAllRequiredPresent() bool {
	if x != nil {
		return x.AllRequiredPresent
	}
	return false
}

func (x *WorkloadVerificationDetails) GetUnknownFiles() []string {
	if x != nil {
		return x.UnknownFiles
	}
	return nil
}

func (x *WorkloadVerificationDetails) GetMissingFiles() []string {
	if x != nil {
		return x.MissingFiles
	}
	return nil
}

// SetReferenceValuesRequest uploads reference values for a container image.
type SetReferenceValuesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image reference (e.g., "docker.io/library/nginx:latest").
	ContainerImage string `protobuf:"bytes,1,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	// Reference values to store.
	ReferenceValues *ReferenceValues `protobuf:"bytes,2,opt,name=reference_values,json=referenceValues,proto3" json:"reference_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetReferenceValuesRequest) Reset() {
	*x = SetReferenceValuesRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceValuesRequest) ProtoMessage() {}

func (x *SetReferenceValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceValuesRequest.ProtoReflect.Descriptor instead.
func (*SetReferenceValuesRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *SetReferenceValuesRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *SetReferenceValuesRequest) GetReferenceValues() *ReferenceValues {
	if x != nil {
		return x.ReferenceValues
	}
	return nil
}

// SetReferenceValuesResponse confirms the upload.
type SetReferenceValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceValuesResponse) Reset() {
	*x = SetReferenceValuesResponse{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceValuesResponse) ProtoMessage() {}

func (x *SetReferenceValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceValuesResponse.ProtoReflect.Descriptor instead.
func (*SetReferenceValuesResponse) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *SetReferenceValuesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetReferenceValuesRequest retrieves reference values.
type GetReferenceValuesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerImage string                 `protobuf:"bytes,1,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetReferenceValuesRequest) Reset() {
	*x = GetReferenceValuesRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferenceValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferenceValuesRequest) ProtoMessage() {}

func (x *GetReferenceValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferenceValuesRequest.ProtoReflect.Descriptor instead.
func (*GetReferenceValuesRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{5}
}

func (x *GetReferenceValuesRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

// ReferenceValues contains expected measurements for a container image.
type ReferenceValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image this applies to.
	ContainerImage string `protobuf:"bytes,1,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	// Individual file reference entries.
	Entries []*ReferenceEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// Timestamp when these values were recorded.
	CreatedAt     int64 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceValues) Reset() {
	*x = ReferenceValues{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceValues) ProtoMessage() {}

func (x *ReferenceValues) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceValues.ProtoReflect.Descriptor instead.
func (*ReferenceValues) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{6}
}

func (x *ReferenceValues) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *ReferenceValues) GetEntries() []*ReferenceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReferenceValues) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ReferenceEntry is a single expected file measurement.
type ReferenceEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expected file path in the container.
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// Expected SHA-384 digest (hex-encoded).
	ExpectedDigest string `protobuf:"bytes,2,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	// Whether this file is required (must be present for TRUSTED verdict).
	Required      bool `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceEntry) Reset() {
	*x = ReferenceEntry{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceEntry) ProtoMessage() {}

func (x *ReferenceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceEntry.ProtoReflect.Descriptor instead.
func (*ReferenceEntry) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{7}
}

func (x *ReferenceEntry) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReferenceEntry) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *ReferenceEntry) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// HealthRequest checks service health.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{8}
}

// HealthResponse returns health status.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// UpdateLatestVerdictRequest force-updates latest verdicts for subjects.
type UpdateLatestVerdictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject identities, e.g. "cgroup://<path>".
	Subjects      []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Verdict       Verdict  `protobuf:"varint,2,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	Message       string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PolicyAction  string   `protobuf:"bytes,4,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	Source        string   `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLatestVerdictRequest) Reset() {
	*x = UpdateLatestVerdictRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLatestVerdictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLatestVerdictRequest) ProtoMessage() {}

func (x *UpdateLatestVerdictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLatestVerdictRequest.ProtoReflect.Descriptor instead.
func (*UpdateLatestVerdictRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLatestVerdictRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *UpdateLatestVerdictRequest) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *UpdateLatestVerdictRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateLatestVerdictRequest) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

func (x *UpdateLatestVerdictRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// UpdateLatestVerdictResponse confirms how many subjects were updated.
type UpdateLatestVerdictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       uint32                 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLatestVerdictResponse) Reset() {
	*x = UpdateLatestVerdictResponse{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLatestVerdictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLatestVerdictResponse) ProtoMessage() {}

func (x *UpdateLatestVerdictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLatestVerdictResponse.ProtoReflect.Descriptor instead.
func (*UpdateLatestVerdictResponse) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLatestVerdictResponse) GetUpdated() uint32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

// GetLatestVerdictRequest queries latest verdict for a subject.
type GetLatestVerdictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject identity, e.g. "cgroup://<path>".
	Subject       string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVerdictRequest) Reset() {
	*x = GetLatestVerdictRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVerdictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVerdictRequest) ProtoMessage() {}

func (x *GetLatestVerdictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVerdictRequest.ProtoReflect.Descriptor instead.
func (*GetLatestVerdictRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{12}
}

func (x *GetLatestVerdictRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// GetLatestVerdictResponse contains the latest known verdict for a subject.
type GetLatestVerdictResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Verdict          Verdict                `protobuf:"varint,2,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PolicyAction     string                 `protobuf:"bytes,4,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	AttestationToken string                 `protobuf:"bytes,5,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	VerifiedAt       int64                  `protobuf:"varint,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Version          uint64                 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Source           string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLatestVerdictResponse) Reset() {
	*x = GetLatestVerdictResponse{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVerdictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVerdictResponse) ProtoMessage() {}

func (x *GetLatestVerdictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVerdictResponse.ProtoReflect.Descriptor instead.
func (*GetLatestVerdictResponse) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{13}
}

func (x *GetLatestVerdictResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *GetLatestVerdictResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

func (x *GetLatestVerdictResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetLatestVerdictResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetLatestVerdictResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// WatchVerdictUpdatesRequest subscribes to verdict updates.
type WatchVerdictUpdatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional subject filter. Empty => all subjects.
	Subjects []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Optional minimum version cursor. Updates with version <= after_version
	// are omitted from the stream.
	AfterVersion  uint64 `protobuf:"varint,2,opt,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVerdictUpdatesRequest) Reset() {
	*x = WatchVerdictUpdatesRequest{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVerdictUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVerdictUpdatesRequest) ProtoMessage() {}

func (x *WatchVerdictUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVerdictUpdatesRequest.ProtoReflect.Descriptor instead.
func (*WatchVerdictUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{14}
}

func (x *WatchVerdictUpdatesRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *WatchVerdictUpdatesRequest) GetAfterVersion() uint64 {
	if x != nil {
		return x.AfterVersion
	}
	return 0
}

// VerdictUpdate is emitted on each verdict change.
type VerdictUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Verdict          Verdict                `protobuf:"varint,2,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PolicyAction     string                 `protobuf:"bytes,4,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	AttestationToken string                 `protobuf:"bytes,5,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	VerifiedAt       int64                  `protobuf:"varint,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Version          uint64                 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Source           string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerdictUpdate) Reset() {
	*x = VerdictUpdate{}
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerdictUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerdictUpdate) ProtoMessage() {}

func (x *VerdictUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_attestationproto_v1_attestation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerdictUpdate.ProtoReflect.Descriptor instead.
func (*VerdictUpdate) Descriptor() ([]byte, []int) {
	return file_attestationproto_v1_attestation_proto_rawDescGZIP(), []int{15}
}

func (x *VerdictUpdate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *VerdictUpdate) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *VerdictUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerdictUpdate) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

func (x *VerdictUpdate) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

func (x *VerdictUpdate) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

func (x *VerdictUpdate) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *VerdictUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VerdictUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_attestationproto_v1_attestation_proto protoreflect.FileDescriptor

const file_attestationproto_v1_attestation_proto_rawDesc = "" +
	"\n" +
	"%attestationproto/v1/attestation.proto\x12\x0eattestation.v1\"\xa6\x01\n" +
	"\x15VerifyWorkloadRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x19\n" +
	"\btd_quote\x18\x02 \x01(\fR\atdQuote\x12\x1b\n" +
	"\tevent_log\x18\x03 \x01(\fR\beventLog\x12\x1b\n" +
	"\tnonce_hex\x18\x04 \x01(\tR\bnonceHex\x12\x17\n" +
	"\apeer_pk\x18\x05 \x01(\fR\x06peerPk\"\xfe\x01\n" +
	"\x16VerifyWorkloadResponse\x121\n" +
	"\averdict\x18\x01 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11attestation_token\x18\x03 \x01(\tR\x10attestationToken\x12E\n" +
	"\adetails\x18\x04 \x01(\v2+.attestation.v1.WorkloadVerificationDetailsR\adetails\x12#\n" +
	"\rpolicy_action\x18\x05 \x01(\tR\fpolicyAction\"\xc7\x03\n" +
	"\x1bWorkloadVerificationDetails\x122\n" +
	"\x15quote_signature_valid\x18\x01 \x01(\bR\x13quoteSignatureValid\x12<\n" +
	"\x1aquote_verification_skipped\x18\x02 \x01(\bR\x18quoteVerificationSkipped\x12\x1f\n" +
	"\vtcb_matches\x18\x03 \x01(\bR\n" +
	"tcbMatches\x12*\n" +
	"\x11report_data_valid\x18\x04 \x01(\bR\x0freportDataValid\x12#\n" +
	"\rmatched_count\x18\x05 \x01(\x05R\fmatchedCount\x12#\n" +
	"\runknown_count\x18\x06 \x01(\x05R\funknownCount\x12#\n" +
	"\rmissing_count\x18\a \x01(\x05R\fmissingCount\x120\n" +
	"\x14all_required_present\x18\b \x01(\bR\x12allRequiredPresent\x12#\n" +
	"\runknown_files\x18\t \x03(\tR\funknownFiles\x12#\n" +
	"\rmissing_files\x18\n" +
	" \x03(\tR\fmissingFiles\"\x90\x01\n" +
	"\x19SetReferenceValuesRequest\x12'\n" +
	"\x0fcontainer_image\x18\x01 \x01(\tR\x0econtainerImage\x12J\n" +
	"\x10reference_values\x18\x02 \x01(\v2\x1f.attestation.v1.ReferenceValuesR\x0freferenceValues\"6\n" +
	"\x1aSetReferenceValuesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x19GetReferenceValuesRequest\x12'\n" +
	"\x0fcontainer_image\x18\x01 \x01(\tR\x0econtainerImage\"\x93\x01\n" +
	"\x0fReferenceValues\x12'\n" +
	"\x0fcontainer_image\x18\x01 \x01(\tR\x0econtainerImage\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.attestation.v1.ReferenceEntryR\aentries\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"q\n" +
	"\x0eReferenceEntry\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12'\n" +
	"\x0fexpected_digest\x18\x02 \x01(\tR\x0eexpectedDigest\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\x0f\n" +
	"\rHealthRequest\"i\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\xc2\x01\n" +
	"\x1aUpdateLatestVerdictRequest\x12\x1a\n" +
	"\bsubjects\x18\x01 \x03(\tR\bsubjects\x121\n" +
	"\averdict\x18\x02 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rpolicy_action\x18\x04 \x01(\tR\fpolicyAction\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"7\n" +
	"\x1bUpdateLatestVerdictResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\rR\aupdated\"3\n" +
	"\x17GetLatestVerdictRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"\xc5\x02\n" +
	"\x18GetLatestVerdictResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x121\n" +
	"\averdict\x18\x02 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rpolicy_action\x18\x04 \x01(\tR\fpolicyAction\x12+\n" +
	"\x11attestation_token\x18\x05 \x01(\tR\x10attestationToken\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\x03R\n" +
	"verifiedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x04R\aversion\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"]\n" +
	"\x1aWatchVerdictUpdatesRequest\x12\x1a\n" +
	"\bsubjects\x18\x01 \x03(\tR\bsubjects\x12#\n" +
	"\rafter_version\x18\x02 \x01(\x04R\fafterVersion\"\xba\x02\n" +
	"\rVerdictUpdate\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x121\n" +
	"\averdict\x18\x02 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rpolicy_action\x18\x04 \x01(\tR\fpolicyAction\x12+\n" +
	"\x11attestation_token\x18\x05 \x01(\tR\x10attestationToken\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\x03R\n" +
	"verifiedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x04R\aversion\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source*v\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fVERDICT_TRUSTED\x10\x01\x12\x15\n" +
	"\x11VERDICT_UNTRUSTED\x10\x02\x12\x11\n" +
	"\rVERDICT_STALE\x10\x03\x12\x13\n" +
	"\x0fVERDICT_UNKNOWN\x10\x042\xc8\x05\n" +
	"\x12AttestationService\x12_\n" +
	"\x0eVerifyWorkload\x12%.attestation.v1.VerifyWorkloadRequest\x1a&.attestation.v1.VerifyWorkloadResponse\x12k\n" +
	"\x12SetReferenceValues\x12).attestation.v1.SetReferenceValuesRequest\x1a*.attestation.v1.SetReferenceValuesResponse\x12`\n" +
	"\x12GetReferenceValues\x12).attestation.v1.GetReferenceValuesRequest\x1a\x1f.attestation.v1.ReferenceValues\x12G\n" +
	"\x06Health\x12\x1d.attestation.v1.HealthRequest\x1a\x1e.attestation.v1.HealthResponse\x12n\n" +
	"\x13UpdateLatestVerdict\x12*.attestation.v1.UpdateLatestVerdictRequest\x1a+.attestation.v1.UpdateLatestVerdictResponse\x12e\n" +
	"\x10GetLatestVerdict\x12'.attestation.v1.GetLatestVerdictRequest\x1a(.attestation.v1.GetLatestVerdictResponse\x12b\n" +
	"\x13WatchVerdictUpdates\x12*.attestation.v1.WatchVerdictUpdatesRequest\x1a\x1d.attestation.v1.VerdictUpdate0\x01BPZNkubevirt.io/kubevirt/pkg/virt-handler/trustd/attestationproto/v1;attestationv1b\x06proto3"

var (
	file_attestationproto_v1_attestation_proto_rawDescOnce sync.Once
	file_attestationproto_v1_attestation_proto_rawDescData []byte
)

func file_attestationproto_v1_attestation_proto_rawDescGZIP() []byte {
	file_attestationproto_v1_attestation_proto_rawDescOnce.Do(func() {
		file_attestationproto_v1_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestationproto_v1_attestation_proto_rawDesc), len(file_attestationproto_v1_attestation_proto_rawDesc)))
	})
	return file_attestationproto_v1_attestation_proto_rawDescData
}

var file_attestationproto_v1_attestation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attestationproto_v1_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_attestationproto_v1_attestation_proto_goTypes = []any{
	(Verdict)(0),                        // 0: attestation.v1.Verdict
	(*VerifyWorkloadRequest)(nil),       // 1: attestation.v1.VerifyWorkloadRequest
	(*VerifyWorkloadResponse)(nil),      // 2: attestation.v1.VerifyWorkloadResponse
	(*WorkloadVerificationDetails)(nil), // 3: attestation.v1.WorkloadVerificationDetails
	(*SetReferenceValuesRequest)(nil),   // 4: attestation.v1.SetReferenceValuesRequest
	(*SetReferenceValuesResponse)(nil),  // 5: attestation.v1.SetReferenceValuesResponse
	(*GetReferenceValuesRequest)(nil),   // 6: attestation.v1.GetReferenceValuesRequest
	(*ReferenceValues)(nil),             // 7: attestation.v1.ReferenceValues
	(*ReferenceEntry)(nil),              // 8: attestation.v1.ReferenceEntry
	(*HealthRequest)(nil),               // 9: attestation.v1.HealthRequest
	(*HealthResponse)(nil),              // 10: attestation.v1.HealthResponse
	(*UpdateLatestVerdictRequest)(nil),  // 11: attestation.v1.UpdateLatestVerdictRequest
	(*UpdateLatestVerdictResponse)(nil), // 12: attestation.v1.UpdateLatestVerdictResponse
	(*GetLatestVerdictRequest)(nil),     // 13: attestation.v1.GetLatestVerdictRequest
	(*GetLatestVerdictResponse)(nil),    // 14: attestation.v1.GetLatestVerdictResponse
	(*WatchVerdictUpdatesRequest)(nil),  // 15: attestation.v1.WatchVerdictUpdatesRequest
	(*VerdictUpdate)(nil),               // 16: attestation.v1.VerdictUpdate
}
var file_attestationproto_v1_attestation_proto_depIdxs = []int32{
	0,  // 0: attestation.v1.VerifyWorkloadResponse.verdict:type_name -> attestation.v1.Verdict
	3,  // 1: attestation.v1.VerifyWorkloadResponse.details:type_name -> attestation.v1.WorkloadVerificationDetails
	7,  // 2: attestation.v1.SetReferenceValuesRequest.reference_values:type_name -> attestation.v1.ReferenceValues
	8,  // 3: attestation.v1.ReferenceValues.entries:type_name -> attestation.v1.ReferenceEntry
	0,  // 4: attestation.v1.UpdateLatestVerdictRequest.verdict:type_name -> attestation.v1.Verdict
	0,  // 5: attestation.v1.GetLatestVerdictResponse.verdict:type_name -> attestation.v1.Verdict
	0,  // 6: attestation.v1.VerdictUpdate.verdict:type_name -> attestation.v1.Verdict
	1,  // 7: attestation.v1.AttestationService.VerifyWorkload:input_type -> attestation.v1.VerifyWorkloadRequest
	4,  // 8: attestation.v1.AttestationService.SetReferenceValues:input_type -> attestation.v1.SetReferenceValuesRequest
	6,  // 9: attestation.v1.AttestationService.GetReferenceValues:input_type -> attestation.v1.GetReferenceValuesRequest
	9,  // 10: attestation.v1.AttestationService.Health:input_type -> attestation.v1.HealthRequest
	11, // 11: attestation.v1.AttestationService.UpdateLatestVerdict:input_type -> attestation.v1.UpdateLatestVerdictRequest
	13, // 12: attestation.v1.AttestationService.GetLatestVerdict:input_type -> attestation.v1.GetLatestVerdictRequest
	15, // 13: attestation.v1.AttestationService.WatchVerdictUpdates:input_type -> attestation.v1.WatchVerdictUpdatesRequest
	2,  // 14: attestation.v1.AttestationService.VerifyWorkload:output_type -> attestation.v1.VerifyWorkloadResponse
	5,  // 15: attestation.v1.AttestationService.SetReferenceValues:output_type -> attestation.v1.SetReferenceValuesResponse
	7,  // 16: attestation.v1.AttestationService.GetReferenceValues:output_type -> attestation.v1.ReferenceValues
	10, // 17: attestation.v1.AttestationService.Health:output_type -> attestation.v1.HealthResponse
	12, // 18: attestation.v1.AttestationService.UpdateLatestVerdict:output_type -> attestation.v1.UpdateLatestVerdictResponse
	14, // 19: attestation.v1.AttestationService.GetLatestVerdict:output_type -> attestation.v1.GetLatestVerdictResponse
	16, // 20: attestation.v1.AttestationService.WatchVerdictUpdates:output_type -> attestation.v1.VerdictUpdate
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_attestationproto_v1_attestation_proto_init() }
func file_attestationproto_v1_attestation_proto_init() {
	if File_attestationproto_v1_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestationproto_v1_attestation_proto_rawDesc), len(file_attestationproto_v1_attestation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attestationproto_v1_attestation_proto_goTypes,
		DependencyIndexes: file_attestationproto_v1_attestation_proto_depIdxs,
		EnumInfos:         file_attestationproto_v1_attestation_proto_enumTypes,
		MessageInfos:      file_attestationproto_v1_attestation_proto_msgTypes,
	}.Build()
	File_attestationproto_v1_attestation_proto = out.File
	file_attestationproto_v1_attestation_proto_goTypes = nil
	file_attestationproto_v1_attestation_proto_depIdxs = nil
}
