// Copyright 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//
// gRPC service definition for the Attestation Service (Verifier).
// This is the external Verifier in the IETF RATS architecture (RFC 9334).
// It receives evidence from the CVM Agent (via virt-handler), verifies it
// against reference values, and issues attestation result tokens.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/attestation.proto

package attestationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verdict is the trust verdict for a container.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_TRUSTED     Verdict = 1
	Verdict_VERDICT_UNTRUSTED   Verdict = 2
	Verdict_VERDICT_STALE       Verdict = 3
	Verdict_VERDICT_UNKNOWN     Verdict = 4
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_TRUSTED",
		2: "VERDICT_UNTRUSTED",
		3: "VERDICT_STALE",
		4: "VERDICT_UNKNOWN",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_TRUSTED":     1,
		"VERDICT_UNTRUSTED":   2,
		"VERDICT_STALE":       3,
		"VERDICT_UNKNOWN":     4,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_attestation_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_v1_attestation_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{0}
}

// VerifyRequest contains the attestation evidence to verify.
type VerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container identifier (cgroup path).
	CgroupPath string `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	// VMI name and namespace for correlation.
	VmiName      string `protobuf:"bytes,2,opt,name=vmi_name,json=vmiName,proto3" json:"vmi_name,omitempty"`
	VmiNamespace string `protobuf:"bytes,3,opt,name=vmi_namespace,json=vmiNamespace,proto3" json:"vmi_namespace,omitempty"`
	// Current RTMR3 value (hex-encoded SHA-384).
	Rtmr3 string `protobuf:"bytes,4,opt,name=rtmr3,proto3" json:"rtmr3,omitempty"`
	// Initial RTMR3 value (hex-encoded SHA-384).
	InitialRtmr3 string `protobuf:"bytes,5,opt,name=initial_rtmr3,json=initialRtmr3,proto3" json:"initial_rtmr3,omitempty"`
	// Ordered measurement log entries.
	Measurements []*MeasurementEntry `protobuf:"bytes,6,rep,name=measurements,proto3" json:"measurements,omitempty"`
	// Challenge nonce (hex-encoded).
	Nonce string `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Reportdata = SHA384(nonce || rtmr3), hex-encoded.
	ReportData string `protobuf:"bytes,8,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	// Optional: TDX TD Quote (binary).
	TdQuote []byte `protobuf:"bytes,9,opt,name=td_quote,json=tdQuote,proto3" json:"td_quote,omitempty"`
	// Container image reference (e.g., "docker.io/library/nginx:latest").
	ContainerImage string `protobuf:"bytes,10,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_v1_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *VerifyRequest) GetVmiName() string {
	if x != nil {
		return x.VmiName
	}
	return ""
}

func (x *VerifyRequest) GetVmiNamespace() string {
	if x != nil {
		return x.VmiNamespace
	}
	return ""
}

func (x *VerifyRequest) GetRtmr3() string {
	if x != nil {
		return x.Rtmr3
	}
	return ""
}

func (x *VerifyRequest) GetInitialRtmr3() string {
	if x != nil {
		return x.InitialRtmr3
	}
	return ""
}

func (x *VerifyRequest) GetMeasurements() []*MeasurementEntry {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *VerifyRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *VerifyRequest) GetReportData() string {
	if x != nil {
		return x.ReportData
	}
	return ""
}

func (x *VerifyRequest) GetTdQuote() []byte {
	if x != nil {
		return x.TdQuote
	}
	return nil
}

func (x *VerifyRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

// MeasurementEntry is a single file measurement.
type MeasurementEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"` // SHA-384 hex
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`     // file path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementEntry) Reset() {
	*x = MeasurementEntry{}
	mi := &file_v1_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementEntry) ProtoMessage() {}

func (x *MeasurementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementEntry.ProtoReflect.Descriptor instead.
func (*MeasurementEntry) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *MeasurementEntry) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *MeasurementEntry) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// VerifyResponse contains the verification result.
type VerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trust verdict.
	Verdict Verdict `protobuf:"varint,1,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	// Human-readable message explaining the verdict.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// JWT attestation result token (signed by the service).
	// Contains the verdict, evidence hash, and timestamp.
	AttestationToken string `protobuf:"bytes,3,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	// Details about what matched/mismatched.
	Details *VerificationDetails `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	// Policy-selected remediation action for this verdict (`none|alert|restart|kill`).
	PolicyAction  string `protobuf:"bytes,5,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_v1_attestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyResponse) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *VerifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyResponse) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

func (x *VerifyResponse) GetDetails() *VerificationDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *VerifyResponse) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

// VerificationDetails provides insight into the verification process.
type VerificationDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether RTMR3 replay matched the reported value.
	Rtmr3ReplayValid bool `protobuf:"varint,1,opt,name=rtmr3_replay_valid,json=rtmr3ReplayValid,proto3" json:"rtmr3_replay_valid,omitempty"`
	// Whether all required reference values were found in measurements.
	AllRequiredPresent bool `protobuf:"varint,2,opt,name=all_required_present,json=allRequiredPresent,proto3" json:"all_required_present,omitempty"`
	// Number of measurements matching reference values.
	MatchedCount int32 `protobuf:"varint,3,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	// Number of measurements not in reference values (unknown files).
	UnknownCount int32 `protobuf:"varint,4,opt,name=unknown_count,json=unknownCount,proto3" json:"unknown_count,omitempty"`
	// Number of required reference values missing from measurements.
	MissingCount int32 `protobuf:"varint,5,opt,name=missing_count,json=missingCount,proto3" json:"missing_count,omitempty"`
	// Whether the TD Quote signature is valid.
	QuoteSignatureValid bool `protobuf:"varint,6,opt,name=quote_signature_valid,json=quoteSignatureValid,proto3" json:"quote_signature_valid,omitempty"`
	// Whether quote verification was skipped (insecure mode).
	QuoteVerificationSkipped bool `protobuf:"varint,7,opt,name=quote_verification_skipped,json=quoteVerificationSkipped,proto3" json:"quote_verification_skipped,omitempty"`
	// List of unknown files found in measurements.
	UnknownFiles []string `protobuf:"bytes,8,rep,name=unknown_files,json=unknownFiles,proto3" json:"unknown_files,omitempty"`
	// List of required files missing from measurements.
	MissingFiles  []string `protobuf:"bytes,9,rep,name=missing_files,json=missingFiles,proto3" json:"missing_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationDetails) Reset() {
	*x = VerificationDetails{}
	mi := &file_v1_attestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationDetails) ProtoMessage() {}

func (x *VerificationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationDetails.ProtoReflect.Descriptor instead.
func (*VerificationDetails) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationDetails) GetRtmr3ReplayValid() bool {
	if x != nil {
		return x.Rtmr3ReplayValid
	}
	return false
}

func (x *VerificationDetails) GetAllRequiredPresent() bool {
	if x != nil {
		return x.AllRequiredPresent
	}
	return false
}

func (x *VerificationDetails) GetMatchedCount() int32 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *VerificationDetails) GetUnknownCount() int32 {
	if x != nil {
		return x.UnknownCount
	}
	return 0
}

func (x *VerificationDetails) GetMissingCount() int32 {
	if x != nil {
		return x.MissingCount
	}
	return 0
}

func (x *VerificationDetails) GetQuoteSignatureValid() bool {
	if x != nil {
		return x.QuoteSignatureValid
	}
	return false
}

func (x *VerificationDetails) GetQuoteVerificationSkipped() bool {
	if x != nil {
		return x.QuoteVerificationSkipped
	}
	return false
}

func (x *VerificationDetails) GetUnknownFiles() []string {
	if x != nil {
		return x.UnknownFiles
	}
	return nil
}

func (x *VerificationDetails) GetMissingFiles() []string {
	if x != nil {
		return x.MissingFiles
	}
	return nil
}

// SetReferenceValuesRequest uploads reference values for a container image.
type SetReferenceValuesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image reference (e.g., "docker.io/library/nginx:latest").
	ContainerImage string `protobuf:"bytes,1,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	// Reference values to store.
	ReferenceValues *ReferenceValues `protobuf:"bytes,2,opt,name=reference_values,json=referenceValues,proto3" json:"reference_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetReferenceValuesRequest) Reset() {
	*x = SetReferenceValuesRequest{}
	mi := &file_v1_attestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceValuesRequest) ProtoMessage() {}

func (x *SetReferenceValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceValuesRequest.ProtoReflect.Descriptor instead.
func (*SetReferenceValuesRequest) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *SetReferenceValuesRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *SetReferenceValuesRequest) GetReferenceValues() *ReferenceValues {
	if x != nil {
		return x.ReferenceValues
	}
	return nil
}

// SetReferenceValuesResponse confirms the upload.
type SetReferenceValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceValuesResponse) Reset() {
	*x = SetReferenceValuesResponse{}
	mi := &file_v1_attestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceValuesResponse) ProtoMessage() {}

func (x *SetReferenceValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceValuesResponse.ProtoReflect.Descriptor instead.
func (*SetReferenceValuesResponse) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{5}
}

func (x *SetReferenceValuesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetReferenceValuesRequest retrieves reference values.
type GetReferenceValuesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerImage string                 `protobuf:"bytes,1,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetReferenceValuesRequest) Reset() {
	*x = GetReferenceValuesRequest{}
	mi := &file_v1_attestation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferenceValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferenceValuesRequest) ProtoMessage() {}

func (x *GetReferenceValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferenceValuesRequest.ProtoReflect.Descriptor instead.
func (*GetReferenceValuesRequest) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{6}
}

func (x *GetReferenceValuesRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

// ReferenceValues contains expected measurements for a container image.
type ReferenceValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image this applies to.
	ContainerImage string `protobuf:"bytes,1,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	// Individual file reference entries.
	Entries []*ReferenceEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// Timestamp when these values were recorded.
	CreatedAt     int64 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceValues) Reset() {
	*x = ReferenceValues{}
	mi := &file_v1_attestation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceValues) ProtoMessage() {}

func (x *ReferenceValues) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceValues.ProtoReflect.Descriptor instead.
func (*ReferenceValues) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{7}
}

func (x *ReferenceValues) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *ReferenceValues) GetEntries() []*ReferenceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReferenceValues) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ReferenceEntry is a single expected file measurement.
type ReferenceEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expected file path in the container.
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// Expected SHA-384 digest (hex-encoded).
	ExpectedDigest string `protobuf:"bytes,2,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	// Whether this file is required (must be present for TRUSTED verdict).
	Required      bool `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceEntry) Reset() {
	*x = ReferenceEntry{}
	mi := &file_v1_attestation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceEntry) ProtoMessage() {}

func (x *ReferenceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceEntry.ProtoReflect.Descriptor instead.
func (*ReferenceEntry) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{8}
}

func (x *ReferenceEntry) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReferenceEntry) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *ReferenceEntry) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// HealthRequest checks service health.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_v1_attestation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{9}
}

// HealthResponse returns health status.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_v1_attestation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// GetLatestVerdictRequest queries latest verdict for a subject.
type GetLatestVerdictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject identity, e.g. "cgroup://<path>".
	Subject       string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVerdictRequest) Reset() {
	*x = GetLatestVerdictRequest{}
	mi := &file_v1_attestation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVerdictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVerdictRequest) ProtoMessage() {}

func (x *GetLatestVerdictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVerdictRequest.ProtoReflect.Descriptor instead.
func (*GetLatestVerdictRequest) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{11}
}

func (x *GetLatestVerdictRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// GetLatestVerdictResponse contains the latest known verdict for a subject.
type GetLatestVerdictResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Verdict          Verdict                `protobuf:"varint,2,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PolicyAction     string                 `protobuf:"bytes,4,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	AttestationToken string                 `protobuf:"bytes,5,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	VerifiedAt       int64                  `protobuf:"varint,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Version          uint64                 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Source           string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLatestVerdictResponse) Reset() {
	*x = GetLatestVerdictResponse{}
	mi := &file_v1_attestation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVerdictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVerdictResponse) ProtoMessage() {}

func (x *GetLatestVerdictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVerdictResponse.ProtoReflect.Descriptor instead.
func (*GetLatestVerdictResponse) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{12}
}

func (x *GetLatestVerdictResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *GetLatestVerdictResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

func (x *GetLatestVerdictResponse) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

func (x *GetLatestVerdictResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetLatestVerdictResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetLatestVerdictResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// WatchVerdictUpdatesRequest subscribes to verdict updates.
type WatchVerdictUpdatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional subject filter. Empty => all subjects.
	Subjects []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Optional minimum version cursor. Updates with version <= after_version
	// are omitted from the stream.
	AfterVersion  uint64 `protobuf:"varint,2,opt,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVerdictUpdatesRequest) Reset() {
	*x = WatchVerdictUpdatesRequest{}
	mi := &file_v1_attestation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVerdictUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVerdictUpdatesRequest) ProtoMessage() {}

func (x *WatchVerdictUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVerdictUpdatesRequest.ProtoReflect.Descriptor instead.
func (*WatchVerdictUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{13}
}

func (x *WatchVerdictUpdatesRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *WatchVerdictUpdatesRequest) GetAfterVersion() uint64 {
	if x != nil {
		return x.AfterVersion
	}
	return 0
}

// VerdictUpdate is emitted on each verdict change.
type VerdictUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Verdict          Verdict                `protobuf:"varint,2,opt,name=verdict,proto3,enum=attestation.v1.Verdict" json:"verdict,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PolicyAction     string                 `protobuf:"bytes,4,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	AttestationToken string                 `protobuf:"bytes,5,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	VerifiedAt       int64                  `protobuf:"varint,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Version          uint64                 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Source           string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerdictUpdate) Reset() {
	*x = VerdictUpdate{}
	mi := &file_v1_attestation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerdictUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerdictUpdate) ProtoMessage() {}

func (x *VerdictUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_attestation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerdictUpdate.ProtoReflect.Descriptor instead.
func (*VerdictUpdate) Descriptor() ([]byte, []int) {
	return file_v1_attestation_proto_rawDescGZIP(), []int{14}
}

func (x *VerdictUpdate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *VerdictUpdate) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *VerdictUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerdictUpdate) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

func (x *VerdictUpdate) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

func (x *VerdictUpdate) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

func (x *VerdictUpdate) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *VerdictUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VerdictUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_v1_attestation_proto protoreflect.FileDescriptor

const file_v1_attestation_proto_rawDesc = "" +
	"\n" +
	"\x14v1/attestation.proto\x12\x0eattestation.v1\"\xec\x02\n" +
	"\rVerifyRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\x12\x19\n" +
	"\bvmi_name\x18\x02 \x01(\tR\avmiName\x12#\n" +
	"\rvmi_namespace\x18\x03 \x01(\tR\fvmiNamespace\x12\x14\n" +
	"\x05rtmr3\x18\x04 \x01(\tR\x05rtmr3\x12#\n" +
	"\rinitial_rtmr3\x18\x05 \x01(\tR\finitialRtmr3\x12D\n" +
	"\fmeasurements\x18\x06 \x03(\v2 .attestation.v1.MeasurementEntryR\fmeasurements\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x1f\n" +
	"\vreport_data\x18\b \x01(\tR\n" +
	"reportData\x12\x19\n" +
	"\btd_quote\x18\t \x01(\fR\atdQuote\x12'\n" +
	"\x0fcontainer_image\x18\n" +
	" \x01(\tR\x0econtainerImage\">\n" +
	"\x10MeasurementEntry\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\"\xee\x01\n" +
	"\x0eVerifyResponse\x121\n" +
	"\averdict\x18\x01 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11attestation_token\x18\x03 \x01(\tR\x10attestationToken\x12=\n" +
	"\adetails\x18\x04 \x01(\v2#.attestation.v1.VerificationDetailsR\adetails\x12#\n" +
	"\rpolicy_action\x18\x05 \x01(\tR\fpolicyAction\"\xa0\x03\n" +
	"\x13VerificationDetails\x12,\n" +
	"\x12rtmr3_replay_valid\x18\x01 \x01(\bR\x10rtmr3ReplayValid\x120\n" +
	"\x14all_required_present\x18\x02 \x01(\bR\x12allRequiredPresent\x12#\n" +
	"\rmatched_count\x18\x03 \x01(\x05R\fmatchedCount\x12#\n" +
	"\runknown_count\x18\x04 \x01(\x05R\funknownCount\x12#\n" +
	"\rmissing_count\x18\x05 \x01(\x05R\fmissingCount\x122\n" +
	"\x15quote_signature_valid\x18\x06 \x01(\bR\x13quoteSignatureValid\x12<\n" +
	"\x1aquote_verification_skipped\x18\a \x01(\bR\x18quoteVerificationSkipped\x12#\n" +
	"\runknown_files\x18\b \x03(\tR\funknownFiles\x12#\n" +
	"\rmissing_files\x18\t \x03(\tR\fmissingFiles\"\x90\x01\n" +
	"\x19SetReferenceValuesRequest\x12'\n" +
	"\x0fcontainer_image\x18\x01 \x01(\tR\x0econtainerImage\x12J\n" +
	"\x10reference_values\x18\x02 \x01(\v2\x1f.attestation.v1.ReferenceValuesR\x0freferenceValues\"6\n" +
	"\x1aSetReferenceValuesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x19GetReferenceValuesRequest\x12'\n" +
	"\x0fcontainer_image\x18\x01 \x01(\tR\x0econtainerImage\"\x93\x01\n" +
	"\x0fReferenceValues\x12'\n" +
	"\x0fcontainer_image\x18\x01 \x01(\tR\x0econtainerImage\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.attestation.v1.ReferenceEntryR\aentries\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"q\n" +
	"\x0eReferenceEntry\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12'\n" +
	"\x0fexpected_digest\x18\x02 \x01(\tR\x0eexpectedDigest\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\x0f\n" +
	"\rHealthRequest\"i\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"3\n" +
	"\x17GetLatestVerdictRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"\xc5\x02\n" +
	"\x18GetLatestVerdictResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x121\n" +
	"\averdict\x18\x02 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rpolicy_action\x18\x04 \x01(\tR\fpolicyAction\x12+\n" +
	"\x11attestation_token\x18\x05 \x01(\tR\x10attestationToken\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\x03R\n" +
	"verifiedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x04R\aversion\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"]\n" +
	"\x1aWatchVerdictUpdatesRequest\x12\x1a\n" +
	"\bsubjects\x18\x01 \x03(\tR\bsubjects\x12#\n" +
	"\rafter_version\x18\x02 \x01(\x04R\fafterVersion\"\xba\x02\n" +
	"\rVerdictUpdate\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x121\n" +
	"\averdict\x18\x02 \x01(\x0e2\x17.attestation.v1.VerdictR\averdict\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rpolicy_action\x18\x04 \x01(\tR\fpolicyAction\x12+\n" +
	"\x11attestation_token\x18\x05 \x01(\tR\x10attestationToken\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\x03R\n" +
	"verifiedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x04R\aversion\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source*v\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fVERDICT_TRUSTED\x10\x01\x12\x15\n" +
	"\x11VERDICT_UNTRUSTED\x10\x02\x12\x11\n" +
	"\rVERDICT_STALE\x10\x03\x12\x13\n" +
	"\x0fVERDICT_UNKNOWN\x10\x042\xd1\x04\n" +
	"\x12AttestationService\x12X\n" +
	"\x17VerifyContainerEvidence\x12\x1d.attestation.v1.VerifyRequest\x1a\x1e.attestation.v1.VerifyResponse\x12k\n" +
	"\x12SetReferenceValues\x12).attestation.v1.SetReferenceValuesRequest\x1a*.attestation.v1.SetReferenceValuesResponse\x12`\n" +
	"\x12GetReferenceValues\x12).attestation.v1.GetReferenceValuesRequest\x1a\x1f.attestation.v1.ReferenceValues\x12G\n" +
	"\x06Health\x12\x1d.attestation.v1.HealthRequest\x1a\x1e.attestation.v1.HealthResponse\x12e\n" +
	"\x10GetLatestVerdict\x12'.attestation.v1.GetLatestVerdictRequest\x1a(.attestation.v1.GetLatestVerdictResponse\x12b\n" +
	"\x13WatchVerdictUpdates\x12*.attestation.v1.WatchVerdictUpdatesRequest\x1a\x1d.attestation.v1.VerdictUpdate0\x01BCZAgithub.com/trustfncall/attestation-service/proto/v1;attestationv1b\x06proto3"

var (
	file_v1_attestation_proto_rawDescOnce sync.Once
	file_v1_attestation_proto_rawDescData []byte
)

func file_v1_attestation_proto_rawDescGZIP() []byte {
	file_v1_attestation_proto_rawDescOnce.Do(func() {
		file_v1_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_attestation_proto_rawDesc), len(file_v1_attestation_proto_rawDesc)))
	})
	return file_v1_attestation_proto_rawDescData
}

var file_v1_attestation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_attestation_proto_goTypes = []any{
	(Verdict)(0),                       // 0: attestation.v1.Verdict
	(*VerifyRequest)(nil),              // 1: attestation.v1.VerifyRequest
	(*MeasurementEntry)(nil),           // 2: attestation.v1.MeasurementEntry
	(*VerifyResponse)(nil),             // 3: attestation.v1.VerifyResponse
	(*VerificationDetails)(nil),        // 4: attestation.v1.VerificationDetails
	(*SetReferenceValuesRequest)(nil),  // 5: attestation.v1.SetReferenceValuesRequest
	(*SetReferenceValuesResponse)(nil), // 6: attestation.v1.SetReferenceValuesResponse
	(*GetReferenceValuesRequest)(nil),  // 7: attestation.v1.GetReferenceValuesRequest
	(*ReferenceValues)(nil),            // 8: attestation.v1.ReferenceValues
	(*ReferenceEntry)(nil),             // 9: attestation.v1.ReferenceEntry
	(*HealthRequest)(nil),              // 10: attestation.v1.HealthRequest
	(*HealthResponse)(nil),             // 11: attestation.v1.HealthResponse
	(*GetLatestVerdictRequest)(nil),    // 12: attestation.v1.GetLatestVerdictRequest
	(*GetLatestVerdictResponse)(nil),   // 13: attestation.v1.GetLatestVerdictResponse
	(*WatchVerdictUpdatesRequest)(nil), // 14: attestation.v1.WatchVerdictUpdatesRequest
	(*VerdictUpdate)(nil),              // 15: attestation.v1.VerdictUpdate
}
var file_v1_attestation_proto_depIdxs = []int32{
	2,  // 0: attestation.v1.VerifyRequest.measurements:type_name -> attestation.v1.MeasurementEntry
	0,  // 1: attestation.v1.VerifyResponse.verdict:type_name -> attestation.v1.Verdict
	4,  // 2: attestation.v1.VerifyResponse.details:type_name -> attestation.v1.VerificationDetails
	8,  // 3: attestation.v1.SetReferenceValuesRequest.reference_values:type_name -> attestation.v1.ReferenceValues
	9,  // 4: attestation.v1.ReferenceValues.entries:type_name -> attestation.v1.ReferenceEntry
	0,  // 5: attestation.v1.GetLatestVerdictResponse.verdict:type_name -> attestation.v1.Verdict
	0,  // 6: attestation.v1.VerdictUpdate.verdict:type_name -> attestation.v1.Verdict
	1,  // 7: attestation.v1.AttestationService.VerifyContainerEvidence:input_type -> attestation.v1.VerifyRequest
	5,  // 8: attestation.v1.AttestationService.SetReferenceValues:input_type -> attestation.v1.SetReferenceValuesRequest
	7,  // 9: attestation.v1.AttestationService.GetReferenceValues:input_type -> attestation.v1.GetReferenceValuesRequest
	10, // 10: attestation.v1.AttestationService.Health:input_type -> attestation.v1.HealthRequest
	12, // 11: attestation.v1.AttestationService.GetLatestVerdict:input_type -> attestation.v1.GetLatestVerdictRequest
	14, // 12: attestation.v1.AttestationService.WatchVerdictUpdates:input_type -> attestation.v1.WatchVerdictUpdatesRequest
	3,  // 13: attestation.v1.AttestationService.VerifyContainerEvidence:output_type -> attestation.v1.VerifyResponse
	6,  // 14: attestation.v1.AttestationService.SetReferenceValues:output_type -> attestation.v1.SetReferenceValuesResponse
	8,  // 15: attestation.v1.AttestationService.GetReferenceValues:output_type -> attestation.v1.ReferenceValues
	11, // 16: attestation.v1.AttestationService.Health:output_type -> attestation.v1.HealthResponse
	13, // 17: attestation.v1.AttestationService.GetLatestVerdict:output_type -> attestation.v1.GetLatestVerdictResponse
	15, // 18: attestation.v1.AttestationService.WatchVerdictUpdates:output_type -> attestation.v1.VerdictUpdate
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_attestation_proto_init() }
func file_v1_attestation_proto_init() {
	if File_v1_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_attestation_proto_rawDesc), len(file_v1_attestation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_attestation_proto_goTypes,
		DependencyIndexes: file_v1_attestation_proto_depIdxs,
		EnumInfos:         file_v1_attestation_proto_enumTypes,
		MessageInfos:      file_v1_attestation_proto_msgTypes,
	}.Build()
	File_v1_attestation_proto = out.File
	file_v1_attestation_proto_goTypes = nil
	file_v1_attestation_proto_depIdxs = nil
}
