// Copyright 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//
// gRPC service definition for trustd.
// trustd runs inside a TDX Confidential VM and bridges kernel
// IMA container measurements to the host-side virt-handler via vsock.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/trustd.proto

package trustdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType mirrors the kernel's IMA_CN_EVENT_* constants.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED    EventType = 0
	EventType_EVENT_TYPE_NEW            EventType = 1
	EventType_EVENT_TYPE_MEASUREMENT    EventType = 2
	EventType_EVENT_TYPE_HEARTBEAT      EventType = 3
	EventType_EVENT_TYPE_HEARTBEAT_MISS EventType = 4
	EventType_EVENT_TYPE_REMOVED        EventType = 5
	EventType_EVENT_TYPE_ATTEST_BEGIN   EventType = 6
	EventType_EVENT_TYPE_ATTEST_END     EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_NEW",
		2: "EVENT_TYPE_MEASUREMENT",
		3: "EVENT_TYPE_HEARTBEAT",
		4: "EVENT_TYPE_HEARTBEAT_MISS",
		5: "EVENT_TYPE_REMOVED",
		6: "EVENT_TYPE_ATTEST_BEGIN",
		7: "EVENT_TYPE_ATTEST_END",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_NEW":            1,
		"EVENT_TYPE_MEASUREMENT":    2,
		"EVENT_TYPE_HEARTBEAT":      3,
		"EVENT_TYPE_HEARTBEAT_MISS": 4,
		"EVENT_TYPE_REMOVED":        5,
		"EVENT_TYPE_ATTEST_BEGIN":   6,
		"EVENT_TYPE_ATTEST_END":     7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_trustd_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_v1_trustd_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{0}
}

// AttestContainerRequest triggers attestation of a specific container.
type AttestContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container identifier (cgroup path inside the CVM).
	CgroupPath string `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	// Nonce from the verifier (hex-encoded). Binds attestation to challenge.
	NonceHex string `protobuf:"bytes,2,opt,name=nonce_hex,json=nonceHex,proto3" json:"nonce_hex,omitempty"`
	// Whether to include a TD Quote in the response.
	IncludeTdQuote bool `protobuf:"varint,3,opt,name=include_td_quote,json=includeTdQuote,proto3" json:"include_td_quote,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttestContainerRequest) Reset() {
	*x = AttestContainerRequest{}
	mi := &file_v1_trustd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestContainerRequest) ProtoMessage() {}

func (x *AttestContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestContainerRequest.ProtoReflect.Descriptor instead.
func (*AttestContainerRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{0}
}

func (x *AttestContainerRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *AttestContainerRequest) GetNonceHex() string {
	if x != nil {
		return x.NonceHex
	}
	return ""
}

func (x *AttestContainerRequest) GetIncludeTdQuote() bool {
	if x != nil {
		return x.IncludeTdQuote
	}
	return false
}

// AttestContainerResponse contains the attestation evidence for one container.
type AttestContainerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container cgroup path.
	CgroupPath string `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	// Current RTMR3 value (hex-encoded, 96 chars for SHA-384).
	Rtmr3 string `protobuf:"bytes,2,opt,name=rtmr3,proto3" json:"rtmr3,omitempty"`
	// Initial RTMR3 value at container creation (hex-encoded).
	InitialRtmr3 string `protobuf:"bytes,3,opt,name=initial_rtmr3,json=initialRtmr3,proto3" json:"initial_rtmr3,omitempty"`
	// Number of measurements extended into RTMR3.
	MeasurementCount int64 `protobuf:"varint,4,opt,name=measurement_count,json=measurementCount,proto3" json:"measurement_count,omitempty"`
	// Individual measurement log entries.
	Measurements []*ContainerMeasurement `protobuf:"bytes,5,rep,name=measurements,proto3" json:"measurements,omitempty"`
	// Reportdata = SHA384(nonce || rtmr3), hex-encoded.
	ReportData string `protobuf:"bytes,6,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	// Nonce echo (hex-encoded).
	Nonce string `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Optional: TDX TD Quote (binary, base64-encoded).
	// Only present if include_td_quote was true in the request.
	TdQuote []byte `protobuf:"bytes,8,opt,name=td_quote,json=tdQuote,proto3" json:"td_quote,omitempty"`
	// Timestamp of the attestation (seconds since epoch).
	Timestamp     int64 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestContainerResponse) Reset() {
	*x = AttestContainerResponse{}
	mi := &file_v1_trustd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestContainerResponse) ProtoMessage() {}

func (x *AttestContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestContainerResponse.ProtoReflect.Descriptor instead.
func (*AttestContainerResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{1}
}

func (x *AttestContainerResponse) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *AttestContainerResponse) GetRtmr3() string {
	if x != nil {
		return x.Rtmr3
	}
	return ""
}

func (x *AttestContainerResponse) GetInitialRtmr3() string {
	if x != nil {
		return x.InitialRtmr3
	}
	return ""
}

func (x *AttestContainerResponse) GetMeasurementCount() int64 {
	if x != nil {
		return x.MeasurementCount
	}
	return 0
}

func (x *AttestContainerResponse) GetMeasurements() []*ContainerMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *AttestContainerResponse) GetReportData() string {
	if x != nil {
		return x.ReportData
	}
	return ""
}

func (x *AttestContainerResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AttestContainerResponse) GetTdQuote() []byte {
	if x != nil {
		return x.TdQuote
	}
	return nil
}

func (x *AttestContainerResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ContainerMeasurement represents a single file measurement.
type ContainerMeasurement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-384 digest of the measured file (hex-encoded).
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Path of the measured file.
	File          string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMeasurement) Reset() {
	*x = ContainerMeasurement{}
	mi := &file_v1_trustd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMeasurement) ProtoMessage() {}

func (x *ContainerMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMeasurement.ProtoReflect.Descriptor instead.
func (*ContainerMeasurement) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerMeasurement) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ContainerMeasurement) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// ListContainersRequest lists all tracked containers.
type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_v1_trustd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{3}
}

// ListContainersResponse contains all tracked container states.
type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerState      `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_v1_trustd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{4}
}

func (x *ListContainersResponse) GetContainers() []*ContainerState {
	if x != nil {
		return x.Containers
	}
	return nil
}

// GetContainerStateRequest queries a specific container.
type GetContainerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStateRequest) Reset() {
	*x = GetContainerStateRequest{}
	mi := &file_v1_trustd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStateRequest) ProtoMessage() {}

func (x *GetContainerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStateRequest.ProtoReflect.Descriptor instead.
func (*GetContainerStateRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{5}
}

func (x *GetContainerStateRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

// ContainerState represents the current state of a tracked container.
type ContainerState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath          string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	Rtmr3               string                 `protobuf:"bytes,2,opt,name=rtmr3,proto3" json:"rtmr3,omitempty"`
	InitialRtmr3        string                 `protobuf:"bytes,3,opt,name=initial_rtmr3,json=initialRtmr3,proto3" json:"initial_rtmr3,omitempty"`
	MeasurementCount    int64                  `protobuf:"varint,4,opt,name=measurement_count,json=measurementCount,proto3" json:"measurement_count,omitempty"`
	LastHeartbeat       int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // seconds since epoch, 0 if never
	HeartbeatCount      int64                  `protobuf:"varint,6,opt,name=heartbeat_count,json=heartbeatCount,proto3" json:"heartbeat_count,omitempty"`
	HeartbeatMonitoring bool                   `protobuf:"varint,7,opt,name=heartbeat_monitoring,json=heartbeatMonitoring,proto3" json:"heartbeat_monitoring,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_v1_trustd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerState) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *ContainerState) GetRtmr3() string {
	if x != nil {
		return x.Rtmr3
	}
	return ""
}

func (x *ContainerState) GetInitialRtmr3() string {
	if x != nil {
		return x.InitialRtmr3
	}
	return ""
}

func (x *ContainerState) GetMeasurementCount() int64 {
	if x != nil {
		return x.MeasurementCount
	}
	return 0
}

func (x *ContainerState) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ContainerState) GetHeartbeatCount() int64 {
	if x != nil {
		return x.HeartbeatCount
	}
	return 0
}

func (x *ContainerState) GetHeartbeatMonitoring() bool {
	if x != nil {
		return x.HeartbeatMonitoring
	}
	return false
}

// WatchEventsRequest subscribes to container events.
type WatchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter to specific event types. Empty = all events.
	EventTypes []EventType `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,proto3,enum=trustd.v1.EventType" json:"event_types,omitempty"`
	// Optional: filter to specific cgroup path. Empty = all containers.
	CgroupPath    string `protobuf:"bytes,2,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_v1_trustd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{7}
}

func (x *WatchEventsRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *WatchEventsRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

// ContainerEvent is streamed to subscribers.
type ContainerEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventType  EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=trustd.v1.EventType" json:"event_type,omitempty"`
	CgroupPath string                 `protobuf:"bytes,2,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	Timestamp  int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// For MEASUREMENT events:
	Digest   string `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Filename string `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	// For HEARTBEAT_MISS:
	Detail string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	// Current RTMR3 at event time (hex):
	Rtmr3            string `protobuf:"bytes,7,opt,name=rtmr3,proto3" json:"rtmr3,omitempty"`
	MeasurementCount int64  `protobuf:"varint,8,opt,name=measurement_count,json=measurementCount,proto3" json:"measurement_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_v1_trustd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ContainerEvent) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *ContainerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ContainerEvent) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ContainerEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ContainerEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ContainerEvent) GetRtmr3() string {
	if x != nil {
		return x.Rtmr3
	}
	return ""
}

func (x *ContainerEvent) GetMeasurementCount() int64 {
	if x != nil {
		return x.MeasurementCount
	}
	return 0
}

// GetTDQuoteRequest asks trustd to obtain a TD Quote.
type GetTDQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Report data to include in the quote (64 bytes, base64-encoded).
	ReportData    []byte `protobuf:"bytes,1,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTDQuoteRequest) Reset() {
	*x = GetTDQuoteRequest{}
	mi := &file_v1_trustd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTDQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTDQuoteRequest) ProtoMessage() {}

func (x *GetTDQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTDQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetTDQuoteRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{9}
}

func (x *GetTDQuoteRequest) GetReportData() []byte {
	if x != nil {
		return x.ReportData
	}
	return nil
}

// GetTDQuoteResponse contains the TD Quote.
type GetTDQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TDX TD Quote (binary).
	TdQuote       []byte `protobuf:"bytes,1,opt,name=td_quote,json=tdQuote,proto3" json:"td_quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTDQuoteResponse) Reset() {
	*x = GetTDQuoteResponse{}
	mi := &file_v1_trustd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTDQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTDQuoteResponse) ProtoMessage() {}

func (x *GetTDQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTDQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetTDQuoteResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{10}
}

func (x *GetTDQuoteResponse) GetTdQuote() []byte {
	if x != nil {
		return x.TdQuote
	}
	return nil
}

// PingRequest is a liveness check.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_v1_trustd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{11}
}

// PingResponse confirms the agent is alive.
type PingResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ContainersTracked int64                  `protobuf:"varint,3,opt,name=containers_tracked,json=containersTracked,proto3" json:"containers_tracked,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_v1_trustd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{12}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *PingResponse) GetContainersTracked() int64 {
	if x != nil {
		return x.ContainersTracked
	}
	return 0
}

// HeartbeatMonitorRequest enables heartbeat timeout detection.
type HeartbeatMonitorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath     string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = use kernel default (90s)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatMonitorRequest) Reset() {
	*x = HeartbeatMonitorRequest{}
	mi := &file_v1_trustd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMonitorRequest) ProtoMessage() {}

func (x *HeartbeatMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMonitorRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatMonitorRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatMonitorRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *HeartbeatMonitorRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// HeartbeatMonitorResponse confirms monitoring was started.
type HeartbeatMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMonitorResponse) Reset() {
	*x = HeartbeatMonitorResponse{}
	mi := &file_v1_trustd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMonitorResponse) ProtoMessage() {}

func (x *HeartbeatMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMonitorResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatMonitorResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{14}
}

// HeartbeatMonitorStopRequest disables heartbeat monitoring.
type HeartbeatMonitorStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMonitorStopRequest) Reset() {
	*x = HeartbeatMonitorStopRequest{}
	mi := &file_v1_trustd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMonitorStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMonitorStopRequest) ProtoMessage() {}

func (x *HeartbeatMonitorStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMonitorStopRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatMonitorStopRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatMonitorStopRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

// HeartbeatMonitorStopResponse confirms monitoring was stopped.
type HeartbeatMonitorStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMonitorStopResponse) Reset() {
	*x = HeartbeatMonitorStopResponse{}
	mi := &file_v1_trustd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMonitorStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMonitorStopResponse) ProtoMessage() {}

func (x *HeartbeatMonitorStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMonitorStopResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatMonitorStopResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{16}
}

// HeartbeatReportRequest reports one liveness heartbeat for a container.
type HeartbeatReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReportRequest) Reset() {
	*x = HeartbeatReportRequest{}
	mi := &file_v1_trustd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReportRequest) ProtoMessage() {}

func (x *HeartbeatReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReportRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatReportRequest) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatReportRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

// HeartbeatReportResponse confirms heartbeat ingestion.
type HeartbeatReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReportResponse) Reset() {
	*x = HeartbeatReportResponse{}
	mi := &file_v1_trustd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReportResponse) ProtoMessage() {}

func (x *HeartbeatReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_trustd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReportResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatReportResponse) Descriptor() ([]byte, []int) {
	return file_v1_trustd_proto_rawDescGZIP(), []int{18}
}

var File_v1_trustd_proto protoreflect.FileDescriptor

const file_v1_trustd_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/trustd.proto\x12\ttrustd.v1\"\x80\x01\n" +
	"\x16AttestContainerRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\x12\x1b\n" +
	"\tnonce_hex\x18\x02 \x01(\tR\bnonceHex\x12(\n" +
	"\x10include_td_quote\x18\x03 \x01(\bR\x0eincludeTdQuote\"\xd7\x02\n" +
	"\x17AttestContainerResponse\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\x12\x14\n" +
	"\x05rtmr3\x18\x02 \x01(\tR\x05rtmr3\x12#\n" +
	"\rinitial_rtmr3\x18\x03 \x01(\tR\finitialRtmr3\x12+\n" +
	"\x11measurement_count\x18\x04 \x01(\x03R\x10measurementCount\x12C\n" +
	"\fmeasurements\x18\x05 \x03(\v2\x1f.trustd.v1.ContainerMeasurementR\fmeasurements\x12\x1f\n" +
	"\vreport_data\x18\x06 \x01(\tR\n" +
	"reportData\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x19\n" +
	"\btd_quote\x18\b \x01(\fR\atdQuote\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"B\n" +
	"\x14ContainerMeasurement\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\"\x17\n" +
	"\x15ListContainersRequest\"S\n" +
	"\x16ListContainersResponse\x129\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x19.trustd.v1.ContainerStateR\n" +
	"containers\";\n" +
	"\x18GetContainerStateRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\"\x9c\x02\n" +
	"\x0eContainerState\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\x12\x14\n" +
	"\x05rtmr3\x18\x02 \x01(\tR\x05rtmr3\x12#\n" +
	"\rinitial_rtmr3\x18\x03 \x01(\tR\finitialRtmr3\x12+\n" +
	"\x11measurement_count\x18\x04 \x01(\x03R\x10measurementCount\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\x12'\n" +
	"\x0fheartbeat_count\x18\x06 \x01(\x03R\x0eheartbeatCount\x121\n" +
	"\x14heartbeat_monitoring\x18\a \x01(\bR\x13heartbeatMonitoring\"l\n" +
	"\x12WatchEventsRequest\x125\n" +
	"\vevent_types\x18\x01 \x03(\x0e2\x14.trustd.v1.EventTypeR\n" +
	"eventTypes\x12\x1f\n" +
	"\vcgroup_path\x18\x02 \x01(\tR\n" +
	"cgroupPath\"\x93\x02\n" +
	"\x0eContainerEvent\x123\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x14.trustd.v1.EventTypeR\teventType\x12\x1f\n" +
	"\vcgroup_path\x18\x02 \x01(\tR\n" +
	"cgroupPath\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x14\n" +
	"\x05rtmr3\x18\a \x01(\tR\x05rtmr3\x12+\n" +
	"\x11measurement_count\x18\b \x01(\x03R\x10measurementCount\"4\n" +
	"\x11GetTDQuoteRequest\x12\x1f\n" +
	"\vreport_data\x18\x01 \x01(\fR\n" +
	"reportData\"/\n" +
	"\x12GetTDQuoteResponse\x12\x19\n" +
	"\btd_quote\x18\x01 \x01(\fR\atdQuote\"\r\n" +
	"\vPingRequest\"~\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12-\n" +
	"\x12containers_tracked\x18\x03 \x01(\x03R\x11containersTracked\"c\n" +
	"\x17HeartbeatMonitorRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"\x1a\n" +
	"\x18HeartbeatMonitorResponse\">\n" +
	"\x1bHeartbeatMonitorStopRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\"\x1e\n" +
	"\x1cHeartbeatMonitorStopResponse\"9\n" +
	"\x16HeartbeatReportRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\"\x19\n" +
	"\x17HeartbeatReportResponse*\xe0\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_NEW\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_MEASUREMENT\x10\x02\x12\x18\n" +
	"\x14EVENT_TYPE_HEARTBEAT\x10\x03\x12\x1d\n" +
	"\x19EVENT_TYPE_HEARTBEAT_MISS\x10\x04\x12\x16\n" +
	"\x12EVENT_TYPE_REMOVED\x10\x05\x12\x1b\n" +
	"\x17EVENT_TYPE_ATTEST_BEGIN\x10\x06\x12\x19\n" +
	"\x15EVENT_TYPE_ATTEST_END\x10\a2\xdf\x06\n" +
	"\x06Trustd\x12X\n" +
	"\x0fAttestContainer\x12!.trustd.v1.AttestContainerRequest\x1a\".trustd.v1.AttestContainerResponse\x12U\n" +
	"\x0eListContainers\x12 .trustd.v1.ListContainersRequest\x1a!.trustd.v1.ListContainersResponse\x12S\n" +
	"\x11GetContainerState\x12#.trustd.v1.GetContainerStateRequest\x1a\x19.trustd.v1.ContainerState\x12R\n" +
	"\x14WatchContainerEvents\x12\x1d.trustd.v1.WatchEventsRequest\x1a\x19.trustd.v1.ContainerEvent0\x01\x12I\n" +
	"\n" +
	"GetTDQuote\x12\x1c.trustd.v1.GetTDQuoteRequest\x1a\x1d.trustd.v1.GetTDQuoteResponse\x127\n" +
	"\x04Ping\x12\x16.trustd.v1.PingRequest\x1a\x17.trustd.v1.PingResponse\x12`\n" +
	"\x15StartHeartbeatMonitor\x12\".trustd.v1.HeartbeatMonitorRequest\x1a#.trustd.v1.HeartbeatMonitorResponse\x12g\n" +
	"\x14StopHeartbeatMonitor\x12&.trustd.v1.HeartbeatMonitorStopRequest\x1a'.trustd.v1.HeartbeatMonitorStopResponse\x12X\n" +
	"\x0fReportHeartbeat\x12!.trustd.v1.HeartbeatReportRequest\x1a\".trustd.v1.HeartbeatReportResponse\x12R\n" +
	"\x10RestartContainer\x12#.trustd.v1.GetContainerStateRequest\x1a\x19.trustd.v1.ContainerStateB@Z>kubevirt.io/kubevirt/pkg/virt-handler/trustd/proto/v1;trustdv1b\x06proto3"

var (
	file_v1_trustd_proto_rawDescOnce sync.Once
	file_v1_trustd_proto_rawDescData []byte
)

func file_v1_trustd_proto_rawDescGZIP() []byte {
	file_v1_trustd_proto_rawDescOnce.Do(func() {
		file_v1_trustd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_trustd_proto_rawDesc), len(file_v1_trustd_proto_rawDesc)))
	})
	return file_v1_trustd_proto_rawDescData
}

var file_v1_trustd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_trustd_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_v1_trustd_proto_goTypes = []any{
	(EventType)(0),                       // 0: trustd.v1.EventType
	(*AttestContainerRequest)(nil),       // 1: trustd.v1.AttestContainerRequest
	(*AttestContainerResponse)(nil),      // 2: trustd.v1.AttestContainerResponse
	(*ContainerMeasurement)(nil),         // 3: trustd.v1.ContainerMeasurement
	(*ListContainersRequest)(nil),        // 4: trustd.v1.ListContainersRequest
	(*ListContainersResponse)(nil),       // 5: trustd.v1.ListContainersResponse
	(*GetContainerStateRequest)(nil),     // 6: trustd.v1.GetContainerStateRequest
	(*ContainerState)(nil),               // 7: trustd.v1.ContainerState
	(*WatchEventsRequest)(nil),           // 8: trustd.v1.WatchEventsRequest
	(*ContainerEvent)(nil),               // 9: trustd.v1.ContainerEvent
	(*GetTDQuoteRequest)(nil),            // 10: trustd.v1.GetTDQuoteRequest
	(*GetTDQuoteResponse)(nil),           // 11: trustd.v1.GetTDQuoteResponse
	(*PingRequest)(nil),                  // 12: trustd.v1.PingRequest
	(*PingResponse)(nil),                 // 13: trustd.v1.PingResponse
	(*HeartbeatMonitorRequest)(nil),      // 14: trustd.v1.HeartbeatMonitorRequest
	(*HeartbeatMonitorResponse)(nil),     // 15: trustd.v1.HeartbeatMonitorResponse
	(*HeartbeatMonitorStopRequest)(nil),  // 16: trustd.v1.HeartbeatMonitorStopRequest
	(*HeartbeatMonitorStopResponse)(nil), // 17: trustd.v1.HeartbeatMonitorStopResponse
	(*HeartbeatReportRequest)(nil),       // 18: trustd.v1.HeartbeatReportRequest
	(*HeartbeatReportResponse)(nil),      // 19: trustd.v1.HeartbeatReportResponse
}
var file_v1_trustd_proto_depIdxs = []int32{
	3,  // 0: trustd.v1.AttestContainerResponse.measurements:type_name -> trustd.v1.ContainerMeasurement
	7,  // 1: trustd.v1.ListContainersResponse.containers:type_name -> trustd.v1.ContainerState
	0,  // 2: trustd.v1.WatchEventsRequest.event_types:type_name -> trustd.v1.EventType
	0,  // 3: trustd.v1.ContainerEvent.event_type:type_name -> trustd.v1.EventType
	1,  // 4: trustd.v1.Trustd.AttestContainer:input_type -> trustd.v1.AttestContainerRequest
	4,  // 5: trustd.v1.Trustd.ListContainers:input_type -> trustd.v1.ListContainersRequest
	6,  // 6: trustd.v1.Trustd.GetContainerState:input_type -> trustd.v1.GetContainerStateRequest
	8,  // 7: trustd.v1.Trustd.WatchContainerEvents:input_type -> trustd.v1.WatchEventsRequest
	10, // 8: trustd.v1.Trustd.GetTDQuote:input_type -> trustd.v1.GetTDQuoteRequest
	12, // 9: trustd.v1.Trustd.Ping:input_type -> trustd.v1.PingRequest
	14, // 10: trustd.v1.Trustd.StartHeartbeatMonitor:input_type -> trustd.v1.HeartbeatMonitorRequest
	16, // 11: trustd.v1.Trustd.StopHeartbeatMonitor:input_type -> trustd.v1.HeartbeatMonitorStopRequest
	18, // 12: trustd.v1.Trustd.ReportHeartbeat:input_type -> trustd.v1.HeartbeatReportRequest
	6,  // 13: trustd.v1.Trustd.RestartContainer:input_type -> trustd.v1.GetContainerStateRequest
	2,  // 14: trustd.v1.Trustd.AttestContainer:output_type -> trustd.v1.AttestContainerResponse
	5,  // 15: trustd.v1.Trustd.ListContainers:output_type -> trustd.v1.ListContainersResponse
	7,  // 16: trustd.v1.Trustd.GetContainerState:output_type -> trustd.v1.ContainerState
	9,  // 17: trustd.v1.Trustd.WatchContainerEvents:output_type -> trustd.v1.ContainerEvent
	11, // 18: trustd.v1.Trustd.GetTDQuote:output_type -> trustd.v1.GetTDQuoteResponse
	13, // 19: trustd.v1.Trustd.Ping:output_type -> trustd.v1.PingResponse
	15, // 20: trustd.v1.Trustd.StartHeartbeatMonitor:output_type -> trustd.v1.HeartbeatMonitorResponse
	17, // 21: trustd.v1.Trustd.StopHeartbeatMonitor:output_type -> trustd.v1.HeartbeatMonitorStopResponse
	19, // 22: trustd.v1.Trustd.ReportHeartbeat:output_type -> trustd.v1.HeartbeatReportResponse
	7,  // 23: trustd.v1.Trustd.RestartContainer:output_type -> trustd.v1.ContainerState
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_trustd_proto_init() }
func file_v1_trustd_proto_init() {
	if File_v1_trustd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_trustd_proto_rawDesc), len(file_v1_trustd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_trustd_proto_goTypes,
		DependencyIndexes: file_v1_trustd_proto_depIdxs,
		EnumInfos:         file_v1_trustd_proto_enumTypes,
		MessageInfos:      file_v1_trustd_proto_msgTypes,
	}.Build()
	File_v1_trustd_proto = out.File
	file_v1_trustd_proto_goTypes = nil
	file_v1_trustd_proto_depIdxs = nil
}
